'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isNum=v=>typeof v==='number'&&Number.isFinite(v);
const num=(v,d=3)=>isNum(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
const stamp=t=>{if(!t)return'尚无';const d=new Date(t);return Number.isNaN(d.getTime())?String(t):new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)+' UTC+8'};
const safeURL=u=>{try{const p=new URL(u);return ['https:','http:'].includes(p.protocol)?p.href:'#'}catch{return'#'}};
let data=null,lastPayload='',busy=false,logFilter='important',logLimit=6;
const names={pro:'MiMo-V2.6 Pro',flash:'MiMo-V2.6 Flash'};
function verified(){return (data?.snapshots||[]).filter(s=>s.verification==='verified'&&s.id&&s.models&&Number.isFinite(Date.parse(s.observed_at))).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at))}
function latestModel(key){const ss=verified();for(let i=ss.length-1;i>=0;i--){if(ss[i].models[key])return {s:ss[i],m:ss[i].models[key]}}return null}
function legacyModel(key){return data?.legacy?.models?.[key]||data?.models?.[key]||{}}
function proofHTML(o){const facts=Array.isArray(o?.facts)?o.facts:[];const ids=Array.isArray(o?.evidence_snapshot_ids)?o.evidence_snapshot_ids:[];const refs=ids.map(id=>(data.snapshots||[]).find(s=>s.id===id)).filter(Boolean);return `<dl><dt>已观察到</dt><dd>${facts.length?'<ul>'+facts.map(f=>'<li>'+esc(f)+'</li>').join('')+'</ul>':esc(o?.summary||'暂无可核验的新数据。')}</dd><dt>可能的解释</dt><dd>${esc(o?.interpretation||'证据不足，暂不推断。')}</dd><dt>不能说明</dt><dd>${esc(o?.limits||'不能由单次读数判断持续进步。')}</dd><dt>下一次看什么</dt><dd>${esc(o?.next_watch||'同口径的新训练记录与外部测验。')}</dd><dt>证据位置</dt><dd>${refs.length?refs.map(s=>`<a href="${esc(safeURL(s.source_url||data.source_url))}" target="_blank" rel="noopener noreferrer">${esc(stamp(s.observed_at))} · ${esc(s.id)}</a>${s.evidence_url?' · <a href="'+esc(safeURL(s.evidence_url))+'" target="_blank" rel="noopener noreferrer">抓取存档</a>':''}`).join('<br>'):'尚无官方数值快照支撑能力判断；详见数据状态与旧版归档。'}</dd></dl>`}
function modelReadings(key,type){const v=latestModel(key),old=legacyModel(key),metric=$('train-metric').value;let value='—',note='等待可核验记录';if(v){if(type==='train'){const rv=v.m.metrics?.[metric];value=metric==='dynsam'&&isNum(rv)?num(rv*100,2)+'%':num(rv);note=`${metric==='dynsam'?'练习尝试成功比例':'平均奖励'} · 第 ${num(v.m.metrics_step,0)} 轮读数`}else{const b=v.m.benchmark||{};value=num(b.value,2)+(isNum(b.value)&&b.unit==='percent'?'%':'');note=`${b.name||'外部测验'}${b.version?' '+b.version:''} · 对应第 ${num(b.checkpoint_step,0)} 轮${b.carried_forward?' · 沿用旧测验':''}`} note+=' · '+stamp(type==='train'?v.s.observed_at:(v.m.benchmark?.observed_at||v.s.observed_at))}else{value=type==='train'?(metric==='dynsam'?old.dynsam??'—':old.reward??'—'):(old.deepswe??'—');note=type==='train'?'早期参考 · 未重新核验':`早期参考 · ${old.deepswe_delta||'测验轮次待核验'}`;}return `<div class="model-reading ${key}"><span class="model-name"><span class="model-dot"></span>${esc(key==='pro'?'Pro':'Flash')}</span><div class="reading">${esc(value)}<small>${esc(note)}</small></div></div>`}
function series(model,type,metric){let candidates=[];
// A backfill is a single retrieval of the official historical series, not past hourly monitoring.
for(const bf of data.backfills||[]){const m=bf.models?.[model];if(bf.verification!=='verified'||!m)continue;const b=m.benchmark||{},key=type==='bench'?b.protocol_id:m.training_series_id;const steps=type==='bench'?b.steps:m.steps;const vals=type==='bench'?b.values:m.metrics?.[metric];if(!key||!m.run_id||!Array.isArray(steps)||!Array.isArray(vals))continue;steps.forEach((step,i)=>{let val=vals[i];if(!isNum(val)||!isNum(step))return;if(type==='train'&&metric==='dynsam')val*=100;candidates.push({value:val,step,time:bf.observed_at,recorded:type==='train'?m.recorded_at?.[i]:null,id:bf.id,group:m.run_id+'|'+key,unit:type==='bench'?b.unit:(metric==='dynsam'?'percent':'score'),backfilled:true})})}
for(const s of verified()){const m=s.models?.[model];if(!m)continue;const b=m.benchmark||{},key=type==='bench'?b.protocol_id:m.training_series_id,step=type==='bench'?b.checkpoint_step:m.metrics_step;let val=type==='bench'?b.value:m.metrics?.[metric];if(type==='train'&&metric==='dynsam'&&isNum(val))val*=100;if(!key||!m.run_id||!isNum(val)||!isNum(step))continue;candidates.push({value:val,step,time:type==='bench'?(b.observed_at||s.observed_at):s.observed_at,recorded:m.metrics_recorded_at,id:s.id,group:m.run_id+'|'+key,unit:type==='bench'?b.unit:(metric==='dynsam'?'percent':'score')})}
if(!candidates.length)return[];const last=candidates[candidates.length-1],grouped=candidates.filter(x=>x.group===last.group&&x.unit===last.unit),unique=new Map();for(const p of grouped)unique.set(p.step,p);return [...unique.values()].sort((a,b)=>a.step-b.step)}
function plot(target,points,model,type){const el=$(target);if(points.length<2){el.innerHTML=`<div class="empty-chart"><span class="empty-mark" aria-hidden="true">⌁</span><strong>${points.length===1?'有一份可比读数，还不是趋势':'不补画一条尚不存在的趋势'}</strong><span>${type==='bench'?'需要至少两个同口径、不同训练轮次的测验结果。':'需要至少两份同一记录序列、不同训练轮次的数值。'}</span>${points.length?'<span>已核验：第 '+num(points[0].step,0)+' 轮，'+num(points[0].value)+'</span>':'<span>有读数后按同口径比较，不补画历史。</span>'}</div>`;return}
const all=points,p=points.slice(-30),a=all[0],b=all[all.length-1],diff=b.value-a.value;const percent=b.unit==='percent'&&p.every(x=>x.value>=0&&x.value<=100);let lo,hi;if(percent){lo=0;hi=100}else{lo=Math.min(...p.map(x=>x.value));hi=Math.max(...p.map(x=>x.value));const margin=Math.max((hi-lo)*.18,Math.abs(hi)*.03,.001);lo-=margin;hi+=margin}const x=v=>48+(v.step-p[0].step)/(p[p.length-1].step-p[0].step)*352,y=v=>161-(v-lo)/(hi-lo)*137;const pts=p.map(v=>`${x(v)},${y(v.value)}`).join(' ');let svg=`<svg viewBox="0 0 425 198" class="chart ${model}" role="img" aria-label="${esc((type==='bench'?'外部测验':'训练读数')+'，从 '+a.value+' 到 '+b.value+'；横轴为训练轮次')}">`;for(let i=0;i<3;i++){const v=lo+(hi-lo)*i/2;svg+=`<line class="gridline" x1="48" x2="402" y1="${y(v)}" y2="${y(v)}"/><text x="40" y="${y(v)+3}" text-anchor="end">${esc(num(v,3))}</text>`}svg+=`<polyline class="line" points="${pts}"/>`+p.map(v=>`<circle class="point" cx="${x(v)}" cy="${y(v.value)}" r="4"><title>第 ${esc(v.step)} 轮：${esc(v.value)}；观测于 ${esc(stamp(v.time))}</title></circle>`).join('')+`<text x="48" y="184">第 ${p[0].step} 轮</text><text x="402" y="184" text-anchor="end">第 ${p[p.length-1].step} 轮</text></svg>`;
let headline=`从 ${num(a.value)} 到 ${num(b.value)}，${diff===0?'读数相同':(diff>0?'增加 ':'减少 ')+num(Math.abs(diff))+(percent?' 个百分点':'')}`;let bars='';if(percent){headline=type==='bench'?(diff===0?'前后测验通过率相同':`按通过率换算，每 100 次尝试${diff>0?'多':'少'}成功约 ${num(Math.abs(diff),2)} 次`):`练习尝试成功比例：${num(a.value,2)}% → ${num(b.value,2)}%`;bars='<div class="bar-pair '+model+'">'+[a,b].map((v,i)=>`<div class="bar-row"><span>${i?'最近':'起点'}</span><div class="bar-track"><div class="bar-fill ${i?'':'before'}" style="width:${v.value}%"></div></div><span>${num(v.value,2)}%</span></div>`).join('')+'</div>'}
el.innerHTML=`<div class="chart-change">${esc(headline)}</div>${bars}${svg}<p class="chart-note">${percent?'通过率刻度 0–100%；不是整体智能增幅。':'纵轴按读数范围展开；不是从零起算。'} 横轴：训练轮次。${all.length>30?'图示最近 30 个点，变化比较该序列首末记录。':''}${all.some(v=>v.backfilled)?' 早期点来自官方历史回溯，并非本网站此前的逐小时采集。':''}${model==='flash'?' Flash 已剔除本次重跑替代的旧记录。':''}</p><details class="expand"><summary>查看前后依据与图中数值</summary><p>比较同一模型、训练段与记录口径。训练任务仍可能变化；两个点的变化不代表统计显著。</p><div class="table-wrap"><table><thead><tr><th>训练轮次</th><th>读数</th><th>取数时间</th></tr></thead><tbody>${p.map(v=>`<tr><td>${num(v.step,0)}</td><td>${num(v.value)}</td><td>${esc(stamp(v.time))}</td></tr>`).join('')}</tbody></table></div></details>`}
function renderCharts(){if(!data)return;$('training-readings').innerHTML=modelReadings('pro','train')+modelReadings('flash','train');plot('train-chart',series($('train-model').value,'train',$('train-metric').value),$('train-model').value,'train');plot('bench-chart',series($('bench-model').value,'bench'),$('bench-model').value,'bench')}
function processCard(key){const v=latestModel(key),old=legacyModel(key),m=v?.m;const fresh=v&&Date.now()-Date.parse(v.s.observed_at)<2*3600000&&data.monitor?.status==='ok';const phase=fresh?m.phase:'unknown';const phaseIndex={rollout:1,rewarding:2,training:3}[phase]??-1;const state=fresh?({rollout:'正在尝试完成任务',rewarding:'正在检查与评分',training:'正在更新模型参数',stopped:'公开状态：已停止',unknown:'阶段未确认'}[phase]||'阶段未确认'):'最近阶段待核验';const phaseText=m?.phase_note||({rollout:'模型正在执行任务并收集尝试；这还不等于已经完成参数更新。',rewarding:'检查尝试结果，为后续更新提供奖励反馈。',training:'根据收集的经验与奖励信号，调整模型参数。'}[phase]||`历史参考：${old.phase||'暂无'}。不据此高亮当前阶段。`);const cost=m?.metrics?.cost_usd,turn=m?.metrics?.turns;return `<article class="panel ${key}"><div class="phase-top"><span class="model-name"><span class="model-dot"></span>${esc(names[key])}</span><span class="numeric">${m?'已完成 '+num(m.completed_steps,0)+' 轮':'早期参考 · 第 '+esc(old.step??'—')+' 轮中'}</span></div><h3 class="spacer-top">${m&&isNum(m.current_step)?'第 '+num(m.current_step,0)+' 轮 · ':''}${esc(state)}</h3><div class="steps">${['接到任务','尝试完成','检查结果','更新模型'].map((s,i)=>`<div class="step ${i===phaseIndex?'active':''}" ${i===phaseIndex?'aria-current="step"':''}><span>0${i+1}</span><b>${s}</b></div>`).join('')}</div><p class="phase-note">${esc(phaseText)}</p><div class="mini-data"><span>平均交互 <b>${m?num(turn,1):esc(old.turns??'—')} 轮</b></span><span>已披露成本 <b>${m?(isNum(cost)?'$'+num(cost,0):'—'):esc(old.cost??'—')}</b></span></div><p class="chart-note">${m?'观测于 '+esc(stamp(v.s.observed_at)):'上述数值来自旧版记录，尚未重新核验。'} 阶段是循环，不是总进度。</p></article>`}
function renderLogs(){if(!data)return;const logs=(data.observations||[]).slice().sort((a,b)=>Date.parse(b.time)-Date.parse(a.time));const filtered=logs.filter(o=>logFilter==='all'||o.kind!=='routine');$('timeline').innerHTML=filtered.slice(0,logLimit).map(o=>`<article class="event"><div class="event-time"><span>${esc(stamp(o.time))}</span><span>${esc(({data_quality:'数据说明',benchmark:'测验更新',training:'训练观察',incident:'运行事件',routine:'例行检查',milestone:'关键事件'})[o.kind]||'观察记录')}</span></div><h3>${esc(o.title)}</h3><p>${esc(o.summary)}</p><details class="evidence"><summary>展开事实、解释与下一次关注</summary>${proofHTML(o)}</details></article>`).join('')||'<p class="blank-label">暂时没有新的关键观察。可切换“全部检查”查看每次记录。</p>';$('more').hidden=filtered.length<=logLimit}
const metricDefs=[['平均奖励','reward','critic/rewards/mean','分数'],['练习尝试平均成功比例','dynsam','dynsam/avg@n','ratio'],['全失败题组比例','passrate_zero','dynsam/passrate/zero','ratio'],['全成功题组比例','passrate_one','dynsam/passrate/one','ratio'],['策略逐 Token 熵','entropy','actor/entropy_loss','数值'],['策略梯度损失','pg_loss','actor/pg_loss','数值'],['梯度范数','grad_norm','actor/grad_norm','数值'],['训练/推理差异','kl','train_infer_diff/new_infer/kl','数值'],['平均上下文','context_tokens','ctx_total_length/mean','tokens'],['平均交互轮数','turns','dynsam/agg_turn/mean','轮'],['基础设施错误比例','infra_error_rate','dynsam/infra_error/seq_rate','ratio'],['单轮耗时','step_seconds','timing_s/step','秒'],['生成耗时','rollout_seconds','timing_s/outer_gen','秒'],['参数更新耗时','train_seconds','timing_s/trainer_ops','秒'],['累计 Tokens','total_tokens','total_tokens','tokens'],['累计成本','cost_usd','cost_usd','USD'],['训练样本量','samples','samples_trained','条'],['已接纳任务','accepted','accepted','项'],['已评判任务','evaluated','evaluated','项']];
function rawValue(key,k,unit){const v=latestModel(key)?.m?.metrics?.[k];if(!isNum(v))return'—';const approx=latestModel(key)?.m?.approximate_metrics?.includes(k)?'≈':'';return approx+(unit==='ratio'?num(v*100,3)+'%':num(v,['reward','dynsam','entropy','pg_loss','grad_norm','kl'].includes(k)?6:2))}
function render(d){data=d;const mon=d.monitor||{},o=d.analysis||{},ss=verified();$('headline').textContent=o.headline||'先看证据，再判断进步。';$('hero-summary').textContent=o.summary||'正在积累可以比较的训练记录。';const ok=mon.status==='ok';$('status-label').textContent=ok?'有已核验记录':'数据核验中';$('status-label').className='pill'+(ok?'':' warn');$('answer-progress').textContent=o.answers?.progress||'最近状态尚待核验';$('answer-training').textContent=o.answers?.training||'缺少可比的前后记录';$('answer-benchmark').textContent=o.answers?.benchmark||'等待同口径的新测验';$('last-check').textContent='最近检查：'+stamp(mon.last_attempt_at);$('last-success').textContent='最近成功取数：'+stamp(mon.last_success_at);const stale=mon.last_success_at&&Date.now()-Date.parse(mon.last_success_at)>2*3600000;const message=(!ok?mon.message:'')||(stale?'最近成功取数已超过两小时，请勿当作当前状态。':'');$('data-notice').hidden=!message;$('data-notice').textContent=message;$('hero-evidence-body').innerHTML=proofHTML(o);$('training-readings').innerHTML=modelReadings('pro','train')+modelReadings('flash','train');$('benchmark-readings').innerHTML=modelReadings('pro','bench')+modelReadings('flash','bench');$('process-cards').innerHTML=processCard('pro')+processCard('flash');renderCharts();renderLogs();$('legacy-log').innerHTML=(d.legacy?.history||d.history||[]).map(x=>`<div class="event"><p class="small spacer-top">${esc(x.time)} · 历史归档</p><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div>`).join('')||'<p>暂无旧版记录。</p>';$('raw-caption').textContent=ss.length?'此表仅展示已核验快照中的原始读数；空缺用 — 表示，不作补数。':'尚未取得已核验的官方数值快照。旧版数值只作参考，不填入本表。';$('raw-table').innerHTML='<table><thead><tr><th>指标 / 原字段</th><th>Pro</th><th>Flash</th></tr></thead><tbody>'+metricDefs.map(([label,k,raw,unit])=>`<tr><td>${esc(label)}<br><code>${esc(raw)}</code></td><td class="num">${rawValue('pro',k,unit)}</td><td class="num">${rawValue('flash',k,unit)}</td></tr>`).join('')+'</tbody></table>';$('raw-json').textContent=ss.length?JSON.stringify(ss[ss.length-1],null,2):'尚无已核验快照。原有数据保留在 data.json 的 legacy 字段。';renderFreshness()}
async function load(){if(busy)return;busy=true;$('refresh').disabled=true;const ctl=new AbortController(),timeout=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch('./data.json?t='+Date.now(),{cache:'no-store',signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);const text=await r.text(),d=JSON.parse(text);if(d.schema_version!==2||!Array.isArray(d.snapshots)||!Array.isArray(d.observations))throw Error('数据结构尚未就绪');if(text!==lastPayload){render(d);lastPayload=text}else if(data){renderFreshness()} }catch(e){$('data-notice').hidden=false;$('data-notice').textContent='本次页面取数失败'+(data?'，下方保留上次成功读取的记录':'，不代表模型训练发生故障')+'。可稍后点击“立即刷新”。';$('status-label').textContent='页面数据读取失败';$('status-label').className='pill warn';if(!data){$('headline').textContent='数据暂时未读到，原理可以先看懂。';$('hero-summary').textContent='我们不把加载失败解释成训练停滞。你仍可浏览下面的强化学习交互演示与指标说明。';$('training-readings').textContent='等待数据文件';$('benchmark-readings').textContent='等待数据文件';$('train-chart').innerHTML='<div class="empty-chart">没有数据，不绘制曲线。</div>';$('bench-chart').innerHTML='<div class="empty-chart">没有数据，不绘制曲线。</div>';$('process-cards').textContent='训练阶段尚未读取。';$('timeline').textContent='观察记录尚未读取。'}}finally{clearTimeout(timeout);busy=false;$('refresh').disabled=false}}
function renderFreshness(){const mon=data.monitor||{};const stale=mon.last_success_at&&Date.now()-Date.parse(mon.last_success_at)>2*3600000;const ok=mon.status==='ok';$('status-label').textContent=stale?'记录已过期':ok?'有已核验记录':'数据核验中';$('status-label').className='pill'+(!ok||stale?' warn':'');$('data-notice').hidden=ok&&!stale;$('data-notice').textContent=stale?'最近成功取数已超过两小时，不代表当前训练状态。':mon.message||'';$('process-cards').innerHTML=processCard('pro')+processCard('flash')}
const labModes={mixed:{wins:[1,3,6,8,11,14],heading:'有差异，才知道该鼓励哪类尝试。',text:'在这个例子里，有些尝试通过测试，有些没有。成功尝试的奖励高于组内平均，失败尝试则低于平均，从而形成相对更新信号。'},all:{wins:Array.from({length:16},(_,i)=>i),heading:'全部通过，是好结果，但比较信号为零。',text:'假设奖励只有通过 1 分、失败 0 分，这 16 次都是 1 分。仅靠这个奖励，组内无法区分哪次尝试更好；不等于这些任务在所有训练方法里都没用。'},none:{wins:[],heading:'这批尝试，还没有找到成功路径。',text:'这 16 次都是 0 分，也没有组内奖励差异。这只能说明本次采样没有成功，不代表模型永远做不到。可以改进探索、反馈或任务选择。'}};
let labMode='mixed',selectedAttempt=1;
function renderLab(){const cfg=labModes[labMode],wins=cfg.wins;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===labMode)));$('attempts').innerHTML=Array.from({length:16},(_,i)=>{const pass=wins.includes(i);return `<button type="button" class="attempt ${pass?'success':'fail'}" data-attempt="${i}" aria-pressed="${i===selectedAttempt}" aria-label="第 ${i+1} 次模拟尝试，${pass?'成功':'失败'}"><span aria-hidden="true">${pass?'✓':'×'}</span><small>${String(i+1).padStart(2,'0')}</small></button>`}).join('');$('lab-count').innerHTML=`<strong>${wins.length} 次成功</strong> · ${16-wins.length} 次失败 <span aria-hidden="true">／</span> 每个方块是一条假想的尝试`;$('lab-heading').textContent=cfg.heading;$('lab-explanation').textContent=cfg.text;const pass=wins.includes(selectedAttempt);$('trajectory-title').textContent=`第 ${String(selectedAttempt+1).padStart(2,'0')} 次 · ${pass?'成功操作示例':'失败操作示例'} · 非内部思维过程`;$('trajectory').innerHTML=(pass?['复现登录错误，查看相关代码。','修改密码比较逻辑。','运行测试：登录与原有功能均通过。']:['查看登录错误，修改页面提示。','没有修复实际的密码比较逻辑。','运行测试：登录仍失败。']).map(t=>'<li>'+esc(t)+'</li>').join('');const mean=wins.length/16;$('formula').textContent=`通过 = 1，失败 = 0\n本组平均奖励 = ${wins.length} ÷ 16 = ${mean}\n所选尝试的相对反馈 = ${pass?1:0} − ${mean} = ${(pass?1:0)-mean}`}
document.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]');if(mode){labMode=mode.dataset.mode;selectedAttempt=labModes[labMode].wins[0]??0;renderLab()}const at=e.target.closest('[data-attempt]');if(at){selectedAttempt=Number(at.dataset.attempt);renderLab();$('attempts').querySelector(`[data-attempt="${selectedAttempt}"]`)?.focus({preventScroll:true})}const filter=e.target.closest('[data-filter]');if(filter){logFilter=filter.dataset.filter;logLimit=6;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===filter)));renderLogs()}});
['train-model','train-metric','bench-model'].forEach(id=>$(id).addEventListener('change',renderCharts));$('more').addEventListener('click',()=>{logLimit+=10;renderLogs()});$('refresh').addEventListener('click',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});renderLab();load();setInterval(()=>{if(!document.hidden)load()},60000);
