/* Visual walkthrough for the existing schema v2. Reads data; never writes it. */
(() => {
'use strict';
const el=id=>document.getElementById(id), n=v=>typeof v==='number'&&Number.isFinite(v), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=(v,d=0)=>n(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
const stamp=t=>{const d=new Date(t);return t&&Number.isFinite(+d)?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)+' 北京时间':'时间未确认'};
const svg=(body,label)=>`<svg viewBox="0 0 230 176" role="img" aria-label="${esc(label)}">${body}</svg>`;
const successes=new Set([1,3,6,8,11,14]);
function illustration(i){
 if(i===0)return svg(`<ellipse cx="115" cy="152" rx="72" ry="10" fill="#243e3510"/><g class="v-paper"><rect x="59" y="33" width="122" height="112" rx="8" fill="#e2e7dc" transform="rotate(9 115 90)"/><rect x="48" y="27" width="122" height="112" rx="8" fill="#f0f1e8" stroke="#cdd6c8" transform="rotate(-6 110 85)"/><rect x="53" y="22" width="126" height="114" rx="8" fill="#fffef8" stroke="#b8c5b6"/><rect x="53" y="22" width="126" height="25" rx="8" fill="#e6edde"/><circle cx="66" cy="35" r="3" fill="#809a77"/><text x="77" y="39" font-size="10" fill="#56624e">任务卡 · 示意</text><text x="66" y="72" font-size="13" fill="#263b34">修复登录故障</text><path d="M66 86h95M66 95h72" stroke="#d5dbcf" stroke-width="3" stroke-linecap="round"/><rect x="64" y="109" width="104" height="16" rx="4" fill="#f6eadb"/><text x="72" y="120" font-size="9" fill="#926540">正确密码也登不进</text></g>`, '一叠待完成的任务卡');
 if(i===1)return svg(`<path d="M115 35v13M29 51h172M29 51v8M86 51v8M143 51v8M201 51v8" stroke="#b8cbbb" fill="none"/><rect x="82" y="8" width="66" height="30" rx="10" fill="#263f36"/><text x="115" y="28" text-anchor="middle" font-size="13" fill="#fff">MiMo</text>${Array.from({length:16},(_,j)=>{const x=9+j%4*56,y=59+Math.floor(j/4)*27;return `<g class="v-terminal" style="--delay:${j*75}ms"><rect x="${x}" y="${y}" width="48" height="23" rx="5" fill="#fffefa" stroke="#c7d3c5"/><text x="${x+6}" y="${y+15}" font-size="8" fill="#768a74">${String(j+1).padStart(2,'0')}</text><path d="M${x+23} ${y+9}h17m-17 5h11" stroke="#b2c4ad" stroke-width="2"/></g>`}).join('')}`, '一个模型展开16次不同的尝试');
 if(i===2)return svg(`<rect x="28" y="21" width="175" height="130" rx="10" fill="#fffefa" stroke="#bdcdbb"/><rect x="28" y="21" width="175" height="25" rx="10" fill="#253e35"/><circle cx="41" cy="34" r="3" fill="#bdd1b6"/><text x="52" y="37" font-size="10" fill="#fff">测试程序检查结果</text>${Array.from({length:16},(_,j)=>{const x=44+j%8*18,y=59+Math.floor(j/8)*23,ok=successes.has(j);return `<g class="v-verdict" style="--delay:${j*100}ms"><rect x="${x}" y="${y}" width="14" height="18" rx="4" fill="${ok?'#deedde':'#f3e7d7'}"/><text x="${x+7}" y="${y+13}" font-size="11" text-anchor="middle" fill="${ok?'#38774e':'#9c7341'}">${ok?'✓':'×'}</text></g>`}).join('')}<text x="43" y="128" font-size="11" fill="#38774e">6 次通过</text><text x="121" y="128" font-size="11" fill="#9c7341">10 次未通过</text>`, '教学样例中6次通过和10次失败');
 return svg(`<ellipse cx="115" cy="154" rx="68" ry="9" fill="#243e3510"/><path d="M58 58H39v33H21m151-33h19v33h20M84 31V12m31 19V12m31 19V12M84 130v21m31-21v21m31-21v21" stroke="#b6c9b0" stroke-width="3" fill="none"/><rect x="56" y="32" width="120" height="101" rx="15" fill="#dfe9d7" stroke="#a4bba0"/><rect x="65" y="41" width="102" height="82" rx="9" fill="#29473b"/>${Array.from({length:24},(_,j)=>`<rect class="v-weight" x="${77+j%6*13}" y="${54+Math.floor(j/6)*13}" width="8" height="8" rx="2" fill="${['#80a88a','#acc89a','#486856'][j%3]}" style="--delay:${j*65}ms"/>`).join('')}<text x="115" y="119" font-size="9" text-anchor="middle" fill="#e2efdb">调整参数 → 下一版</text>`, '模型内部的参数发生调整，方格仅为示意');
}
const host=document.getElementById('main'); if(!host)return;
const root=document.createElement('section');root.id='v3';root.className='v3';
root.innerHTML=`<header class="v-intro"><div><p class="v-kicker">MiMo · 可视化训练现场</p><h1>AI 怎么学？<br><em>把一轮训练，放到眼前。</em></h1><p class="v-sub">先看它做事，再看它进步。不认识训练参数，也能看明白。</p></div><div class="v-selector" role="group" aria-label="选择模型"><button data-v-model="pro" aria-pressed="true">Pro<span>看这款模型</span></button><button data-v-model="flash" aria-pressed="false">Flash<span>看这款模型</span></button></div></header>
<div class="v-source"><span class="v-status-dot"></span><span id="v-source-time">正在读取已有观测…</span><span>每小时更新 · 非逐秒直播</span></div>
<section class="v-workshop" aria-labelledby="v-workshop-title"><div class="v-panel-top"><div><span class="v-kicker">01 / 它在做什么</span><h2 id="v-workshop-title">不是背答案，是尝试把事做成。</h2></div><div class="v-play-controls"><button id="v-play" class="v-primary">▶ 播放一轮示意</button><button id="v-next" class="v-secondary">下一步 →</button></div></div><div class="v-scene-label"><span id="v-scene-mode">原理示意 · 图中任务与结果均为虚构</span><span id="v-real-stage">实际阶段待读取</span></div>
<div class="v-stations">${[['领一道任务','先明确要做成什么'],['尝试不同做法','同一道任务，做很多次'],['让结果说话','测试哪些做成了'],['把经验写回模型','更新参数，再练下一轮']].map(([title,sub],i)=>`<button class="v-station" data-v-stage="${i}" aria-pressed="${i===0}"><span class="v-stage-num">0${i+1}</span>${illustration(i)}<strong>${title}</strong><span>${sub}</span>${i<3?'<i class="v-flow-arrow" aria-hidden="true">→</i>':''}</button>`).join('')}</div>
<div class="v-narrator"><span class="v-narrator-icon" aria-hidden="true">↳</span><div aria-live="polite"><h3 id="v-narrator-title"></h3><p id="v-narrator-text"></p></div><span id="v-scene-count" class="v-scene-count">01 / 04</span></div><div class="v-loop"><span aria-hidden="true">↶</span><b>收集尝试 → 得到反馈 → 更新参数</b><span>这一整圈，简化理解为一轮训练。实际环节可能并行。</span></div></section>
<section class="v-journey" id="v3-journey" aria-labelledby="v-journey-title"><div class="v-panel-top"><div><span class="v-kicker">02 / 进度在哪里</span><h2 id="v-journey-title">练到哪一轮，测到哪一轮？</h2><p class="v-hint">上排是训练，下排是已有成绩的测验。点任意一轮看看。</p></div><span class="v-source-tag">真实观测</span></div><div id="v-progress-sentence" class="v-progress-sentence">等待训练轮次…</div><div class="v-tape-scroll" tabindex="0" aria-label="训练与测验双轨，可横向滚动"><div id="v-tape"></div></div><div class="v-tape-legend"><span><i class="v-swatch done"></i>已完成训练</span><span><i class="v-swatch tested"></i>已有测验</span><span><i class="v-swatch pending"></i>尚无测验</span><span>… 之后还有几轮？官方未公布总计划</span></div><div id="v-round-detail" class="v-round-detail" aria-live="polite">选择一轮查看记录。</div><p id="v-series-note" class="v-fine"></p></section>
<section class="v-results" aria-labelledby="v-results-title"><div class="v-panel-top"><div><span class="v-kicker">03 / 进步看得见吗</span><h2 id="v-results-title">练习表现，和测验成绩分开看。</h2></div></div><div class="v-results-grid"><article class="v-waffle-card"><div class="v-card-heading"><h3>这批练习，成功了多少？</h3><span class="v-source-tag">真实比例 · 视觉折算</span></div><div class="v-waffle-body"><div id="v-waffle" class="v-waffle" role="img" aria-label="等待数据"></div><div class="v-waffle-number"><strong id="v-rate">—</strong><span id="v-rate-note">等待已确认的成功比例</span><p id="v-rate-change"></p></div></div><p class="v-fine">100 个小格只表示比例，不是 100 道真实题。指标是每题多次尝试的成功比例，再对题目取平均；不能当作所有任务的正确率。</p></article>
<article class="v-exams"><div class="v-card-heading"><h3>外部测验，成绩怎么变？</h3><span class="v-source-tag">真实成绩单</span></div><div id="v-scorecards" class="v-scorecards"></div><div class="v-exam-scrub"><label for="v-exam-range">拖动翻看每次成绩</label><input type="range" id="v-exam-range" min="0" max="0" value="0" aria-label="翻看历史测验成绩" disabled><span id="v-exam-step"></span></div><p class="v-fine">相同测验口径下比较；分数不是智商，也不擅自换算为通过率。没有新成绩，不等于没有进步。</p></article></div></section>
<section class="v-scale"><div><span class="v-kicker">把刚才的“一道题”放大</span><h3>真实一轮，远不止一次尝试。</h3></div><div class="v-scale-equation" id="v-scale">等待公开训练批次数据</div><p id="v-scale-note" class="v-fine"></p></section>
<aside class="v-discovery"><span class="v-kicker">本次观察 · 独立解读</span><h3 id="v-discovery-title">正在读取分析</h3><p id="v-discovery-text"></p><div class="v-discovery-links"><a href="#headline">看分析依据 ↓</a><a id="v-evidence-link" href="https://mimo.xiaomi.com/rl/" target="_blank" rel="noopener noreferrer">核对数据来源 ↗</a><a href="#learn">动手比较全对／全错 ↓</a></div></aside>`;
host.prepend(root);
// Preserve every original panel, ID and handler; readers can progressively expand it.
const deep=document.createElement('details');deep.id='v3-more';deep.className='v3-more';deep.innerHTML='<summary><span>再往里看一点<strong>完整曲线、每小时分析与原始指标</strong></span><span>展开 ↓</span></summary><div class="v3-detail-body"></div>';
const body=deep.lastElementChild;[...host.children].filter(x=>x!==root&&x.tagName!=='FOOTER').forEach(x=>body.append(x));host.insertBefore(deep,host.querySelector('footer'));
const nav=document.querySelector('.nav nav');if(nav)nav.innerHTML='<a href="#v3">看它怎么学</a><a href="#v3-journey">看进度</a><a href="#journal">每小时解读</a><a href="https://mimo.xiaomi.com/rl/" target="_blank" rel="noopener noreferrer">官方现场 ↗</a>';
let model='pro',stage=0,playing=false,timer=null,dataset=null,lastData=null,selectedRound=null,examIndex=null,lastFresh=null,tapeInitialized=false;
const narrations=[['先领任务，还没有开始学习。','比如修复登录故障。任务给出目标，模型要自己尝试完成；图中只是一个假设的例子。'],['同一道任务，尝试多种做法。','这里展示 16 条示意轨迹。每条可以查看文件、运行工具、修改代码；收集尝试不等于参数已经更新。'],['用结果打分，而不是听它自我评价。','教学例子里 6 次通过、10 次未通过。只用通过=1、失败=0 时，成功与失败相对组均值产生不同方向的反馈。'],['这一步，才把反馈用于更新参数。','示意中的方格代表参数，不是真实权重。训练调整做法出现的概率，不是把成功答案存进去；效果仍要用新测验验证。']];
function showStage(i){stage=i;root.querySelectorAll('[data-v-stage]').forEach((b,k)=>{b.classList.toggle('v-active',k===i);b.setAttribute('aria-pressed',String(k===i));});root.dataset.stage=String(i);el('v-narrator-title').textContent=narrations[i][0];el('v-narrator-text').textContent=narrations[i][1];el('v-scene-count').textContent='0'+(i+1)+' / 04';el('v-scene-mode').textContent=(playing?'正在播放教学示意':'原理示意')+' · 任务、结果与参数方格均非真实日志';}
function stop(){playing=false;clearTimeout(timer);timer=null;root.classList.remove('v-playing');el('v-play').textContent='▶ 重播一轮示意';}
function schedule(){timer=setTimeout(()=>{if(stage===3){stop();el('v-narrator-title').textContent='一轮示意结束。真实训练轮次没有改变。';el('v-scene-mode').textContent='教学演示结束 · 点击任意环节回看';return;}showStage(stage+1);schedule();},4200);}
el('v-play').addEventListener('click',()=>{if(playing){stop();showStage(stage);return;}playing=true;root.classList.add('v-playing');el('v-play').textContent='Ⅱ 暂停演示';showStage(0);schedule();});
el('v-next').addEventListener('click',()=>{stop();showStage((stage+1)%4);});
root.querySelectorAll('[data-v-stage]').forEach(b=>b.addEventListener('click',()=>{stop();showStage(Number(b.dataset.vStage));}));
function last(key){const a=(dataset?.snapshots||[]).filter(s=>s.verification==='verified'&&s.models?.[key]&&Number.isFinite(Date.parse(s.observed_at))).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at));return a.at(-1)||null;}
function points(key,kind,metric='dynsam'){
 const s=last(key),m=s?.models[key];if(!m)return[];const bench=kind==='benchmark',group=bench?m.benchmark?.protocol_id:m.training_series_id;if(!group||!m.run_id)return[];
 const map=new Map();let anchor=-Infinity;
 const bfs=(dataset.backfills||[]).filter(b=>b.verification==='verified'&&b.models?.[key]?.run_id===m.run_id&&(bench?b.models[key].benchmark?.protocol_id:b.models[key].training_series_id)===group).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at));
 const bf=bfs.at(-1);if(bf){const x=bf.models[key],b=x.benchmark||{},ss=bench?b.steps:x.steps,vs=bench?b.values:x.metrics?.[metric];anchor=Date.parse(bf.observed_at);if(Array.isArray(ss)&&Array.isArray(vs))ss.forEach((step,i)=>{if(n(step)&&n(vs[i]))map.set(step,{step,value:vs[i],time:bf.observed_at});});}
 const snaps=(dataset.snapshots||[]).filter(x=>x.verification==='verified'&&Date.parse(x.observed_at)>=anchor).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at));
 for(const x of snaps){const v=x.models?.[key],b=v?.benchmark||{};if(!v||v.run_id!==m.run_id||(bench?b.protocol_id:v.training_series_id)!==group)continue;const step=bench?b.checkpoint_step:v.metrics_step,value=bench?b.value:v.metrics?.[metric];if(n(step)&&n(value))map.set(step,{step,value,time:bench?b.observed_at:x.observed_at});}
 return [...map.values()].filter(p=>bench||!n(m.completed_steps)||p.step<=m.completed_steps).sort((a,b)=>a.step-b.step);
}
function renderTape(m){
 const completed=n(m.completed_steps)?m.completed_steps:null,current=n(m.current_step)?m.current_step:null,bp=points(model,'benchmark'),tp=points(model,'training'),bmap=new Map(bp.map(p=>[p.step,p]));
 if(completed===null&&current===null){el('v-tape').textContent='轮次未确认，不绘制进度。';return;}
 const max=Math.max(completed||0,current||0,bp.at(-1)?.step||0),start=Math.max(1,max-47),steps=Array.from({length:max-start+1},(_,i)=>start+i),known=new Set(tp.map(p=>p.step));
 if(!n(selectedRound)||selectedRound>max||selectedRound<start)selectedRound=m.benchmark?.checkpoint_step||completed||current;
 const roundButton=(step,bench)=>{const record=bmap.get(step);let cls,label,mark;if(bench){cls=record?'tested':'unmeasured';label=record?`第${step}轮，测验${fmt(record.value,2)}分`:`第${step}轮，没有公开测验`;mark=record?'▤':'·';}else{cls=step===current&&step>completed?'running':step<=completed?'done':'unmeasured';label=`第${step}轮，${cls==='done'?'已完成训练':cls==='running'?'采集时正在进行':'未确认'}`;mark=cls==='done'?'✓':cls==='running'?'…':'·';}return `<button class="v-ticket ${cls}" data-v-round="${step}" aria-label="${esc(label)}" aria-pressed="${step===selectedRound}"><b>${step}</b><span>${mark}</span></button>`;};
 el('v-tape').innerHTML=`<div class="v-rail"><span class="v-rail-label">训练更新<small>已完成的轮次</small></span>${steps.map(x=>roundButton(x,false)).join('')}<span class="v-future">…<small>继续往后</small></span></div><div class="v-rail"><span class="v-rail-label">测验成绩<small>有成绩才亮起</small></span>${steps.map(x=>roundButton(x,true)).join('')}<span class="v-future">?<small>总轮数未知</small></span></div>`;
 const tested=m.benchmark?.checkpoint_step,gap=n(tested)&&n(completed)?Math.max(0,completed-tested):null;
 el('v-progress-sentence').innerHTML=`<span>已练完 <b>${fmt(completed)}</b> 轮</span><span class="v-sentence-arrow">→</span><span>采集时在第 <b>${fmt(current)}</b> 轮</span><span class="v-test-limit">最新成绩对应第 <b>${fmt(tested)}</b> 轮${gap!==null&&gap>0?` · 后面 ${gap} 个已完成轮次还没有公开成绩`:''}</span>`;
 el('v-series-note').textContent=(start>1?'仅显示最近 48 轮；':'')+(m.training_series_id?.includes('after-')?'重跑后按当前有效训练段展示，作废轮次不重复累加。':'训练轮数不等于能力高低，Pro 与 Flash 也不是同一起点的赛跑。');
 renderRound();
 if(!tapeInitialized){const sc=root.querySelector('.v-tape-scroll');sc.scrollLeft=Math.max(0,sc.scrollWidth-sc.clientWidth);tapeInitialized=true;}
}
function renderRound(){const s=last(model),m=s?.models[model];if(!m)return;const p=points(model,'training').find(x=>x.step===selectedRound),b=points(model,'benchmark').find(x=>x.step===selectedRound);el('v-round-detail').innerHTML=`<strong>第 ${fmt(selectedRound)} 轮</strong><span>${p?`练习平均成功比例：${fmt(p.value*100,2)}%`:'这轮暂无已确认的练习读数'}</span><span>${b?`外部测验：${fmt(b.value,2)} 分`:'测验成绩尚未公开，不代表这轮没有进步'}</span>`;root.querySelectorAll('[data-v-round]').forEach(x=>x.setAttribute('aria-pressed',String(Number(x.dataset.vRound)===selectedRound)));}
function renderExam(){const s=last(model),m=s?.models[model],ps=points(model,'benchmark');const range=el('v-exam-range');if(!ps.length){el('v-scorecards').innerHTML='<p>没有可核验的测验记录，不填示例成绩。</p>';range.disabled=true;el('v-exam-step').textContent='';return;}
 if(examIndex===null||examIndex>=ps.length)examIndex=ps.length-1;const a=ps[0],b=ps[examIndex],diff=b.value-a.value;range.disabled=ps.length<2;range.max=String(ps.length-1);range.value=String(examIndex);
 el('v-scorecards').innerHTML=`<div class="v-report before"><span>首次已公开测验</span><small>第 ${fmt(a.step)} 轮</small><strong>${fmt(a.value,2)}</strong><em>分</em></div><div class="v-score-delta"><span>${diff>0?'↗':diff<0?'↘':'→'}</span><b>${diff>0?'+':''}${fmt(diff,2)}</b><small>分，不是 %</small></div><div class="v-report after"><span>${examIndex===ps.length-1?'最新已公开测验':'正在翻看的测验'}</span><small>第 ${fmt(b.step)} 轮</small><strong>${fmt(b.value,2)}</strong><em>分</em></div>`;
 el('v-exam-step').textContent=`第 ${b.step} 轮 · ${m.benchmark?.name||'测验'} ${m.benchmark?.version||''} · ${m.benchmark?.aggregation||''}`;
}
function renderWaffle(m){const value=m.metrics?.dynsam,p=points(model,'training'),first=p[0]?.value;const valid=n(value)&&value>=0&&value<=1;el('v-waffle').setAttribute('aria-label',valid?`训练尝试的平均成功比例${fmt(value*100,2)}%，每格代表1个百分点，不是实际任务。`:'没有可核验的训练成功比例');
 el('v-waffle').innerHTML=Array.from({length:100},(_,i)=>{const fill=valid?Math.max(0,Math.min(1,value*100-i))*100:0;return `<span><i style="width:${fill}%"></i></span>`;}).join('');
 el('v-rate').textContent=valid?fmt(value*100,2)+'%':'—';el('v-rate-note').textContent=valid?`第 ${fmt(m.metrics_step)} 轮 · 每题等权平均`:'尚未取得该指标，不补数';el('v-rate-change').textContent=valid&&n(first)?`相较首个记录轮次 ${fmt(first*100,2)}%，变化 ${value>=first?'+':''}${fmt((value-first)*100,2)} 个百分点。任务难度可能不同。`:'';
}
function update(d){dataset=d;const s=last(model);root.dataset.model=model;root.querySelectorAll('[data-v-model]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.vModel===model)));
 if(!s){el('v-source-time').textContent='尚未取得已核验数据；教学示意仍可播放。';el('v-real-stage').textContent='实际阶段：未确认';return;}
 const m=s.models[model],age=Date.now()-Date.parse(s.observed_at),fresh=Number.isFinite(age)&&age>=-60000&&age<=90*60000&&d.monitor?.status==='ok';
 el('v-source-time').textContent=`${model==='pro'?'Pro':'Flash'} · ${stamp(s.observed_at)}${fresh?' 的观测':' 的历史记录（非当前状态）'}`;root.classList.toggle('v-stale',!fresh);
 const words={rollout:'收集尝试',rewarding:'检查与评分',training:'更新模型参数',stopped:'已停止',unknown:'阶段尚未确认'};el('v-real-stage').textContent=`${fresh?'采集时':'上次记录'}：第 ${fmt(m.current_step)} 轮 · ${words[m.phase]||words.unknown}`;
 renderTape(m);renderWaffle(m);renderExam();
 const a=m.metrics||{},prompts=a.prompts_per_step,tries=a.attempts_per_prompt;const valid=n(prompts)&&n(tries)&&prompts>0&&tries>0;
 el('v-scale').innerHTML=valid?`<div><b>${fmt(prompts)}</b><span>个任务</span></div><i>×</i><div><b>${fmt(tries)}</b><span>次尝试 / 任务</span></div><i>=</i><div><b>${fmt(prompts*tries)}</b><span>条名义批次轨迹</span></div>`:'本次快照未包含完整批次配置，不推算尝试总数。';
 el('v-scale-note').textContent=valid?`这是快照中批次配置的乘积，不是此刻同时运行的数量；筛选、重试等会使实际生成量不同。${n(a.turns)?'每条轨迹平均 '+fmt(a.turns,1)+' 次交互，远不止写一句答案。':''}`:'';
 el('v-discovery-title').textContent=d.analysis?.headline||'暂无分析';el('v-discovery-text').textContent=(fresh?'':'以下为最近一次已发布解读，不冒充实时结论。')+(d.analysis?.summary||'');
 try{const u=new URL(s.evidence_url);if(u.protocol==='https:')el('v-evidence-link').href=u.href;}catch{}
}
root.addEventListener('click',e=>{const mb=e.target.closest('[data-v-model]');if(mb){model=mb.dataset.vModel;selectedRound=null;examIndex=null;tapeInitialized=false;if(dataset)update(dataset);}const rb=e.target.closest('[data-v-round]');if(rb){selectedRound=Number(rb.dataset.vRound);renderRound();}});
el('v-exam-range').addEventListener('input',e=>{examIndex=Number(e.target.value);renderExam();});
function openDeep(hash){if(!hash||hash==='#')return;let target;try{target=document.getElementById(decodeURIComponent(hash.slice(1)));}catch{return;}if(target&&deep.contains(target)){deep.open=true;let p=target.parentElement;while(p&&p!==deep){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}}}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a)openDeep(a.getAttribute('href'));});window.addEventListener('hashchange',()=>openDeep(location.hash));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){stop();showStage(stage);}});
// Reuse the already-loaded v2 dataset, without another network poll or schema change.
function sync(){try{if(typeof data==='object'&&data?.schema_version===2){const s=lastData===data?last(model):null;const fresh=s?data.monitor?.status==='ok'&&Date.now()-Date.parse(s.observed_at)<=90*60000:null;if(data!==lastData||fresh!==lastFresh){lastData=data;update(data);const latest=last(model);lastFresh=latest?data.monitor?.status==='ok'&&Date.now()-Date.parse(latest.observed_at)<=90*60000:null;}}}catch(e){console.warn('Visual view could not read dataset:',e.message);}}
showStage(0);sync();setInterval(()=>{if(!document.hidden)sync();},10000);setTimeout(sync,600);setTimeout(sync,1800);openDeep(location.hash);
window.MimoVisual={update,points,last,stop,getState:()=>({model,stage,playing,selectedRound,examIndex})};
})();
